# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 567ce4466c1b1cc4e0dfa01c80c97526fa64b71b3eecea840a2a50ff14311f898bbbebcf88690e26989de6b315cb90b06d86317254790250d948f8f94a34afb6

test:
  secret_key_base: 4e04e7a81d57b7e96e41a5bcdc9d739f28c09ac0d5d549155ae4d295098feb940e9066f4c10f609e70c953c01c829907e1e6e814b385f2ff27aec4591b759ad6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
